services:
  bot_db:
    image: postgres:16-alpine3.20
    container_name: bot_db
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./bot_db/:/var/lib/postgresql/data

  telegram_bot:
    container_name: Tracking
    build:
      context: frontend

    environment:
      - BOT_TOKEN=${TOKEN}

    env_file:
      - .env

    ports:
      - "443:443"

    volumes:
      - ./logs:/usr/logs

    restart: always
    depends_on:
      - app

  app:
    build:
      context: backend
    stop_signal: SIGKILL
    container_name: tracking_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - bot_db
