"""update table habits

Revision ID: b129068368e3
Revises: 59228c09ffc7
Create Date: 2024-08-26 20:19:11.990388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b129068368e3"
down_revision: Union[str, None] = "59228c09ffc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "habitss",
        sa.Column(
            "start_date",
            sa.DateTime(),
            server_default="2024-08-26 17:19:11.858938+00:00",
            nullable=False,
        ),
    )
    op.add_column("habitss", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("habitss", "is_active")
    op.drop_column("habitss", "start_date")
    # ### end Alembic commands ###
