"""add model Tracking

Revision ID: 62d4ddef51f9
Revises: fd4d75e616f2
Create Date: 2024-08-30 22:13:29.097999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d4ddef51f9'
down_revision: Union[str, None] = 'fd4d75e616f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackings',
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default='2024-08-30 19:13:28.976379+00:00', nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackings_habit_id'), 'trackings', ['habit_id'], unique=False)
    op.add_column('habits', sa.Column('number_of_days', sa.Integer(), server_default='21', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'number_of_days')
    op.drop_index(op.f('ix_trackings_habit_id'), table_name='trackings')
    op.drop_table('trackings')
    # ### end Alembic commands ###
