"""added OTO relationship

Revision ID: c3a6d6f05519
Revises: cc18e458690c
Create Date: 2024-09-15 10:07:38.564121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c3a6d6f05519'
down_revision: Union[str, None] = 'cc18e458690c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminds', 'time',
               existing_type=sa.INTEGER(),
               type_=mysql.SMALLINT(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reminds', 'time',
               existing_type=mysql.SMALLINT(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
