"""add unique field

Revision ID: ba785a97f16c
Revises: 014097625a54
Create Date: 2024-08-31 00:46:14.080628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba785a97f16c'
down_revision: Union[str, None] = '014097625a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('trackings_date_key', 'trackings', type_='unique')
    op.create_unique_constraint(None, 'trackings', ['habit_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trackings', type_='unique')
    op.create_unique_constraint('trackings_date_key', 'trackings', ['date'])
    # ### end Alembic commands ###
