"""update table users

Revision ID: ad8b3b0e83fd
Revises: 7d8cc82546c6
Create Date: 2024-08-25 12:49:16.199685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad8b3b0e83fd"
down_revision: Union[str, None] = "7d8cc82546c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_chat_id", sa.BigInteger(), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    op.drop_column("users", "user_chat_id")
    # ### end Alembic commands ###
