"""change otm

Revision ID: fd4d75e616f2
Revises: 8f3b634f261e
Create Date: 2024-08-28 21:59:53.727315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd4d75e616f2"
down_revision: Union[str, None] = "8f3b634f261e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_habits_user_id"), "habits", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_habits_user_id"), table_name="habits")
    # ### end Alembic commands ###
