"""An unnecessary field has been deleted

Revision ID: 4b21ecf90679
Revises: e59d4fdcd5a5
Create Date: 2025-08-24 21:07:35.901113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b21ecf90679'
down_revision: Union[str, None] = 'e59d4fdcd5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
