"""Added field create_at for table Comment

Revision ID: af74c224360a
Revises: 8c0288017c34
Create Date: 2025-08-20 11:20:08.441037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af74c224360a'
down_revision: Union[str, None] = '8c0288017c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
