"""Added an index for searching by token

Revision ID: e59d4fdcd5a5
Revises: b26f8b2813a8
Create Date: 2025-08-23 15:51:53.627881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59d4fdcd5a5'
down_revision: Union[str, None] = 'b26f8b2813a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_token_hash', 'revokedtokens', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_hash', table_name='revokedtokens')
    # ### end Alembic commands ###
