STICKER_PACK_HELLO = [
    "CAACAgIAAxkBAALYKWlZa7u8L_bPd6QtFDKiTrZs--OPAAJMDAACNObhSBNaZB0QioSVOAQ",
    "CAACAgIAAxkBAALYMWlZa-xhCCIXxJfULLr-aoCh2TtgAALGAQACFkJrCkoj1PTJ23lHOAQ",
    "CAACAgIAAxkBAALYNGlZbATfydZ-SsHDdlEen3OO_sgUAAI0AQACUomRIxPN12_1HAdYOAQ",
    "CAACAgIAAxkBAALYOmlZbIQb6V4ITCYmx7afXz-R1jwvAAIRAwAC8-O-CxlunyWezCwkOAQ",
    "CAACAgIAAxkBAALYQGlZbKolM3_MQf9V0KSavhAaWwFkAAJVAgACVp29CqxLLIJPoxXfOAQ",
    "CAACAgIAAxkBAALYQ2lZbLwPgwjjKqPziKrPUyOS-83NAAIBAAOYv4ANbvm9JFNK_B04BA",
    "CAACAgIAAxkBAALYRmlZbNBOjffaCBpkbWJ9EIAcE587AAIYAAMNttIZfrvWCJAMlTw4BA",
    "CAACAgIAAxkBAALYSWlZbNxAPUG9lq30ghGSzFKpGdMoAAIfAANZu_wl6jl0G9k9Npk4BA",
    "CAACAgIAAxkBAALYTGlZbO2j8A3yNGLhkV8Dfs2noEl2AALyDgACILd4SgVaZWmYPAwyOAQ",
    "CAACAgIAAxkBAALYT2lZbPtuMj1md8oP6r4o0cedvsgLAAKLAQACK15TC6NhvGkkNINQOAQ",
    "CAACAgIAAxkBAALYVGlZbSNHrSrA2ZHxa3G6vFtMR8QDAAKECQACGELuCNz-JyU0Mm2AOAQ",
    "CAACAgIAAxkBAALYV2lZbTWRMllLtg9sTQeh8Q7ELySfAALGDgAC-dooSwFV0A_4fYNWOAQ",
    "CAACAgIAAxkBAALYWmlZbUbGgzyHDUthwTo3-2kxqjUjAAL3AQACFkJrCjn2cG-0Y3_EOAQ",
    "CAACAgIAAxkBAALYXWlZbVRzpCbHS1dxVQzmPldCpgjHAAIgAANZu_wlhYqWmghNyX04BA",
    "CAACAgIAAxkBAALYYGlZbWcb1pnMpZaVqULNkjxr7I_qAAKXAAM7YCQUs-NVIets3tk4BA",
    "CAACAgIAAxkBAALYY2lZbXlwlKvbtMTAQHdYF_g8eqK1AAJnAAOWn4wOyQZnzEHbDU84BA",
    "CAACAgIAAxkBAALYZmlZbYj9V4Dc6NG3XYdJ6kURs6sXAAKdAAPkoM4HAAEUn3l41D3JOAQ",
    "CAACAgIAAxkBAALYaWlZbZ-zX7lR2GHIGrXkbIu6164CAAIjAQACMNSdEZ7ZN4GuqlwCOAQ",
    "CAACAgIAAxkBAALYbGlZbatsAbif-bHkr4e5LHkED77zAAJcAANZu_wlj1s_8uLbhRA4BA"
]

STICKER_PACK_DONE = [
    "CAACAgIAAxkBAALXymlZZFyPb1LTMHf8L4oJQy9i8qpaAAJFAANZu_wl-9SkNOET-Os4BA",
    "CAACAgIAAxkBAALXzWlZZIpm_9GewoEnT8ue-dBlggABtgACTQADWbv8JSiBoG3dG4L3OAQ",
    "CAACAgIAAxkBAALX5GlZacXtEEgSxxnlEO-18zb5BpaHAALTCQACGY7gSLsBgARtdZI4OAQ",
    "CAACAgIAAxkBAALX52lZadafxiUOhjybCW1em-no5fQsAAJECwACx9XgSHM4wxpMWg7yOAQ",
    "CAACAgIAAxkBAALX6mlZaea8PoMjKJ5yqqWftqsUo8tDAAKvDAACeePYSFDPWi1DDfU8OAQ",
    "CAACAgIAAxkBAALX8GlZagPDkRmwcKCQni7LVyZ3lU3uAAJGAANSiZEj-P7l5ArVCh04BA",
    "CAACAgIAAxkBAALX82lZalzUw-z0dAkwnZ4ObNcRgS10AAI7AQACFkJrCl-7BJlQlsKeOAQ",
    "CAACAgIAAxkBAALX9mlZanN99BcD4JiIa9ruA0mhwuMoAAIyAQACFkJrCl14SHH8f00VOAQ",
    "CAACAgIAAxkBAALX-WlZaoU35gd_2yu7_jbxLfMdO9hyAAKREgAC_PDhSh05-MbyXYyzOAQ",
    "CAACAgIAAxkBAALX_2lZaqD3btDGHYj7Ml3orkoIvKnwAAJeBQACP5XMCqrWdxMs74w5OAQ",
    "CAACAgIAAxkBAALYAmlZard_GNCqcQtWOu--rxQJ5-a4AAL7CgACbzShSyxq7F1NG7V4OAQ",
    "CAACAgIAAxkBAALYCGlZas22OLPtE0uvk_YcAqwAASP6AQACagADwDZPE_6bl3vsHAfaOAQ",
    "CAACAgIAAxkBAALYC2lZauB2F0PqQ5XqAX_9wM2KdzpCAAIPFQACFxTQSSa7IQ3zHMIJOAQ",
    "CAACAgIAAxkBAALYDmlZavJHw1tyY3ZE2vOcPN6lR4qMAAJSAANgiW0MGnbfz9ckcHA4BA",
    "CAACAgIAAxkBAALYFGlZawcz6OwH-zRVX_KmkKSRPxx8AAIOAAOuxzIK1wH88AlZ_CU4BA",
    "CAACAgIAAxkBAALYF2lZaxxoNBg7kJZrs88F1002kRmgAAJTAAPANk8T_gJ3hXi7rlU4BA",
    "CAACAgIAAxkBAALYGmlZazDYCOz8fbyJ_6kByhaKTtu2AAJSAAPANk8T1Pg830XkRuc4BA",
    "CAACAgIAAxkBAALYHWlZaz46A5NPLYJzDsOvoZHUpzq7AAJIAQACIjeOBP3b9pUDR1QuOAQ",
    "CAACAgIAAxkBAALYIGlZa027Kj9MsSuB0qKOclxMzkMPAAKPAQACK15TC1JZlsxRJSLCOAQ",
    "CAACAgIAAxkBAALYI2lZa1kXuELwquzq0ScPwbLtXHsWAAIbCQACGELuCNy5pdXzSq7IOAQ"
]

STICKER_PACK_NOT_DONE = [
    "CAACAgIAAxkBAALYemlb6v3CwSrQzvr5-68NZfFBcNVeAAJ9AAP3AsgPLsm7Ct3LIkk4BA",
    "CAACAgIAAxkBAALYfWlb6z3-0BL5WvlTeNBcx4Ao7GP0AAJaAgACVp29ClvFwUJa4dm6OAQ",
    "CAACAgIAAxkBAALYgGlb62FTXxwFjlPv0Mkn26ZthnqiAAIWAQACUomRI1hEaMPWbwABODgE",
    "CAACAgIAAxkBAALYjGlb67i2b2AN3iakCbA-bzvVfY5DAAJLAAMoD2oU2g-pBuO5n8s4BA",
    "CAACAgIAAxkBAALYj2lb69FQ-0_5PH9pW4xcPJt8443zAAJUAAOvxlEallJjH6gDA0Y4BA",
    "CAACAgIAAxkBAALYkmlb6_ezl7e9u7v5ONGeuVDLn-khAAJOAQACMNSdEVLMpjaP7HoFOAQ"
]

STICKER_PACK_CRY = [
    "CAACAgIAAxkBAALY8Wlb-wABbEmIm6UOhbmtvEwVRc0baAACVwMAArVx2ga2e7f7gIXrkjgE",
    "CAACAgIAAxkBAALXy2lZZH5GOOupsKGKv7-4txp3cbYuAAJMAANZu_wl9GTHcxfEbV84BA",
    "CAACAgIAAxkBAALY92lb-1jc4KnWm06wJksAAZf-_o-ZigACPgADWbv8JciUxtK8a7dJOAQ",
    "CAACAgIAAxkBAALY-mlb-3T5vX0T1_lIlEyR34WF61M_AAI8AANSiZEjQ4g4olXOsYg4BA",
    "CAACAgIAAxkBAALY_Wlb-43_7_JRd08uxqu6zmpiEnAaAAJ4BQACP5XMCqr9CNxLakY6OAQ",
    "CAACAgIAAxkBAALZAAFpW_unqwnQXEWeTKic4_x8DPKWOgACdQADwDZPE5B0WbJxOIvjOAQ",
    "CAACAgIAAxkBAALZA2lb-8Ktacqby8DpcXKNWd-x07vkAALgAgAC8-O-C4dy-fRVoLJJOAQ",
    "CAACAgIAAxkBAALZBmlb-9jbJk-5mhyexEAMyryprVwdAAINAQACUomRIyPURYx4xMd7OAQ",
    "CAACAgIAAxkBAALZCWlb-_H9CzzFD2IQYbfkjNmhhwG5AAJyAwACbbBCA3yGPGowfXzuOAQ",
    "CAACAgIAAxkBAALZDGlb_AO3WvEHFwhNyaXdR3PiNHDDAAJ3AAPBnGAMYU6eidmeFhU4BA",
    "CAACAgIAAxkBAALZD2lb_BZ30Qlyjy997qT_XgABBKFw6QACJAADr8ZRGtsEQs3YPt8fOAQ",
    "CAACAgIAAxkBAALZEmlb_CcyYsHwq2QDYnaLam5J_NuJAAIlAAPBnGAMsZsU2SseitY4BA",
    "CAACAgIAAxkBAALZFWlb_D13rTIMK9zhM_pn2E5MrrqPAAJ1AANEDc8XcVWhikkqs3k4BA",
    "CAACAgIAAxkBAALZGGlb_FC3PIcccIQ09aBUO9JUqYaCAAJgAANZu_wlqisOv_R9cV84BA",
    "CAACAgIAAxkBAALZHmlb_JB8vn4ReiKf4hfZohNw7djRAAIGAwAC8-O-C0z1G9n29qUYOAQ"
]